### ISSUE TITLE
Specs are broken due to Loofah whitelist

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms-inquiries#168]
Since my previous changes in the def `wrap_content_in_tag` : 
https://github.com/refinery/refinerycms/blob/8d2778944572162be6eef8811c17be28a2cb374f/pages/app/presenters/refinery/pages/section_presenter.rb#L66-L70

Loofah strip placeholders in inputs.

**Comment by anitagraham** [comment]
Is it Loofah?

I think I was loosing placeholders a couple of weeks ago, but didn¹t get to
follow it up.
At this point I would also suspect wymeditor.
(I suspect everyone)
-- 
Anita Graham
anita@joli.com.au

**Comment by bricesanchez** [comment]
It is Loofah. i think i will provide a PR with our own whitelist config, no more Loofah strange whitelist and deps.

**Comment by anitagraham** [comment]
I have done a version of that, but not written tests (or tested it).

-- 
Anita Graham
anita@joli.com.au

From:  Brice Sanchez <notifications@github.com>
Reply-To:  refinery/refinerycms-inquiries
<reply+00060f3e4c2c05a9b5caace8f00e14cafe2d429ffade68a592cf00000001131c4bdc9
2a169ce08b6676a@reply.github.com>
Date:  Wednesday, 6 April 2016 at 12:00 PM
To:  refinery/refinerycms-inquiries
<refinerycms-inquiries@noreply.github.com>
Cc:  Anita Graham <anita@joli.com.au>
Subject:  Re: [refinery/refinerycms-inquiries] Specs are broken due to
Loofah whitelist (#168)


It is Loofah. i think i will provide a PR with our own whitelist config, no
more Loofah strange whitelist and deps.


You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/refinery/refinerycms-inquiries/issues/168#issuecomment-2
06109304>

**Comment by bricesanchez** [comment]
Nice, could you provide a PR ?

Let me know if i could help you :)

**Comment by bricesanchez** [comment]
https://github.com/refinery/refinerycms/pull/3164
